config/routes.rb
Rails.application.routes.draw do

get "", to: 'main#index', as: 'index'
get ":title_en", to: 'main#category', as: 'category'
    
get "test/categorylist", to: 'main#category_list', as: 'category_list'   
get ":title_en/edit", to: 'main#category_edit', as: 'category_edit'
post "test/categorylist", to: 'main#category_add', as: 'category_add'
post ":title_en/edit", to: 'main#category_update', as: 'category_update'
get "test/category_remove.:id", to: 'main#category_remove', as: 'category_remove'
    
post "test/royemail", to: 'roy#royemail', as: 'royemail'
post "test/send_email", to: 'main#send_email', as: 'send_email'
    
    
get "/test/room1", to: 'main#room1', as: 'room1'
get "/test/room2", to: 'main#room2', as: 'room2'
get "/test/room3", to: 'main#room3', as: 'room3'

get "module/header"
get "module/sideMenu"
get "module/footer"

	
  root :to => 'main#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  helper :all
  before_filter :prepare_for_mobile
  after_filter :set_access_control_headers
  
  private 
  
  def mobile_device?
	if session[:mobile_param]
		session[:mobile_param] == "1"
	else
		request.user_agent =~ /Mobile|webOS/
	end
  end
  
  helper_method :mobile_device?
  
  def prepare_for_mobile
	session[:mobile_param] = params[:ua_] if params[:ua_]
	request.format = :mobile if mobile_device? && !request.xhr?
  end
    
      

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  
  def index
    @category_list = Category.select("title_en, title_ch").uniq.where(category: "main")
  end
  

  def category
      @category_list = Category.select("title_en, title_ch").uniq.where(category: "main")
      @category = Category.find_by_title_en(params[:title_en])
  end
    
  def category_list
      @category_list = Category.all
  end
    
  def category_add
      category = Category.new(title_en: params[:title_en], title_ch: params[:title_ch], content: "", category: params[:category], parent: params[:parent])
      category.save

      respond_to do |format|
          format.js
      end
  end
    
  def category_remove
      @category = Category.find(params[:id])
      @category.destroy
      
      respond_to do |format|
          format.js
      end
  end
    
  def category_edit
      @category_list = Category.select("title_en, title_ch").uniq.where(category: "main")
      @category = Category.find_by_title_en(params[:title_en])
      p @category
  end
    
  def send_email
      UserMailer.welcome_email("anxsaiyuki@gmail.com").deliver
      respond_to do |format|
          format.js
      end
  end

    
  def category_update
      p "================================="
      p params[:content]
      Category.find_by_title_en(params[:title_en]).update_attributes(content: params[:content])
      respond_to do |format|
          format.js
      end
  end
    
  def room1
      @category_list = Category.select("title_en, title_ch").uniq.where(category: "main")
  end

  def room2
      @category_list = Category.select("title_en, title_ch").uniq.where(category: "main")
  end

  def room3
      @category_list = Category.select("title_en, title_ch").uniq.where(category: "main")
  end
    
end

app/controllers/module_controller.rb
class ModuleController < ActionController::Base

  
  def sideMenu
  
  end
  
  def footer 
      
  end
    
  def header

  end
    
end

app/controllers/roy_controller.rb
class RoyController < ApplicationController
respond_to :json
    
  def royemail
      p params
      UserMailer.welcome_email(params[:name],params[:phone],params[:email],params[:content]).deliver
      render :json => {:name => "David"}.to_json
      
  end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>馥御產後護理之家</title>
<meta name="keywords" content="馥御產後護理之家" />
<meta name="description" content="馥御產後護理之家" />

    <!--<link rel="stylesheet" href="/assets/css/templatemo_style.css">-->
    <link rel="stylesheet" href="/assets/css/reset.css">
    <link rel="stylesheet" href="/assets/css/bootstrap.css">
    <link rel="stylesheet" href="/assets/css/main.css">
    <link rel="stylesheet" href="/assets/css/detail.css">
    <script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
    <script data-turbolinks-track="true" src="/assets/jquery_ujs.js?body=1"></script>
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css" />

    <link rel="stylesheet" href="/assets/css/redactor.css" />
    <script src="/assets/js/redactor.js"></script>

    <link rel="stylesheet" href="/assets/css/jquery.bxslider.css">

    <script  src="/assets/js/jquery.bxslider.min.js"></script>
  
  
</head>
<body>

<%= yield %>
<div class="col-md-12 col-xs-12 device_change">
<%= link_to "電腦版", :ua_ => 0 %> | <%= link_to "手機板", :ua_ => 1 %>
</div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0;" />
	<link rel="stylesheet" href="/assets/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/af.ui.base.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/icons.css" />
	<link rel="stylesheet" href="/assets/css/main-mobile.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/mobile_detail.css" />
	<script data-main="/assets/js/main-mobile.js" src="/assets/js/lib/require.js" charset="utf-8" type="text/javascript"></script>
	<style>
	.leftmenu {
		border-right: 1px solid white;
	}
	.SliderTab{
		background-color: black;
		color: white;
	}
	ul.list {
		text-align: center;
	}
	.device_change {
		text-align: center;
	}
	</style>
    

</head>
<body> 

<div id="afui">
    
    <!--Left Side Menu Navigation bar -->
    <nav>
        <ul class="list">
			<li class="Slider-Title" >選項</li>
                <% @category_list.each do |category_list| %>
                    <li class="sidebar_list"><%= link_to category_list.title_ch, category_path(:title_en => category_list.title_en) %></li>       
                <% end %>
        </ul>
    </nav>


        <div id="content" style="">

            <!--Main Pages-->
            <div class="panel" title="Home" id="home" data-header="top-header" data-footer="none" selected="true">
				<header>
					<a onclick='$.ui.toggleLeftSideMenu()' class='menuButton leftmenu' style="float:left"></a>

				    <a href=".." class="home_button">
							<div class="home_button_top"></div>
							<div class="home_button_bottom"></div>
				    </a>
                    <a href="..">
                        <img src="/assets/img/logo_400x120.png" alt="logo" width="90px" style="margin-left: 15px; padding-top: 5px;" />
                        <img src="/assets/img/logo_2.png" alt="logo2" width="90px" style="float: right; margin-right: 4px; padding-top: 5px;"/>
                    </a>
				</header>
                <div class="menu">
                    <img src="/assets/img/border.jpg" height="130px" style="margin-left:-11px; width: 105.65%;"/>

                </div>
			<%= yield %>
			
			<div id="Loading_mask" class="load_mask", style="display: none;"></div>
			<div id="add_cart"></div>
			<div class="col-md-12 col-xs-12 device_change">
			<%= link_to "電腦版", :ua_ => 0 %> | <%= link_to "手機板", :ua_ => 1 %>
			</div>
		</div>


		</div>

</div>
</body>
</html>    

app/views/main/category.html.erb
<div id="main">

        <%= render partial: "module/header" %>
        
        <div class="col-md-12 col-xs-12 content">
            
            <%= render partial: "module/sideMenu" %>

            <div class="col-md-9 col-xs-9 info">
                
                <div class="info_top"> </div>
                    <% if @category.title_en == "service" or @category.title_en == "medteam" or @category.title_en == "meal" %>
                    <div class="info_mid" style="height:initial;">  
                    <% else %>
                    <div class="info_mid"> 
                    <% end %>
                    <%=raw @category.content %>
                    </div>
               
                
                </div>
             <div class="col-md-12 col-xs-12 info_bottom"></div>
        </div>
    </div>
	    
</div>
            
    <%= render partial: "module/footer" %>

app/views/main/category.mobile.erb
<div class="info_top"> </div>
<div class="info_mid"> 
<%=raw @category.content %>
</div>

<div class="col-md-12 col-xs-12 info_bottom"></div>

app/views/main/category_edit.html.erb
<script>
$(document).ready(
    function()
    {
        $('#redactor').redactor();
    }
);
</script>
<style>
.redactor_box {
    width: 106%;
    height: 100%;
}
</style>
<div id="main">

        <%= render partial: "module/header" %>
        
        <div class="col-md-12 col-xs-12 content">
            
            <%= render partial: "module/sideMenu" %>

            <div class="col-md-9 col-xs-9 info">
                
                <div class="info_top"> </div>

                    <div class="info_mid" style="height:initial;">  
                    <%= form_tag category_update_path, remote: true do %>
                    <textarea id="redactor" name="content">
                        
                        <%=raw @category.content %>
                        
					</textarea>
                        <%= submit_tag "Update Quantity" %>
                    <% end %>
                    </div>
               
                
                </div>
             <div class="col-md-12 col-xs-12 info_bottom"></div>
        </div>
    </div>
    <div class="update_alert" style="color:red;"></div>
</div>
            
    <%= render partial: "module/footer" %>

app/views/main/category_list.html.erb
<div>
<div class="col-md-12 col-xs-12">
        <div class="col-md-2 col-xs-2">Title En</div>
        <div class="col-md-2 col-xs-2">Title Ch</div>
        <div class="col-md-2 col-xs-2">Category</div>
        <div class="col-md-2 col-xs-2">Parent</div>
        <div class="col-md-4 col-xs-4">Option</div>
<% @category_list.each do |category_list| %>
    
        <div class="col-md-2 col-xs-2">
            <%= category_list.title_en %>

        </div>
        <div class="col-md-2 col-xs-2">
            <%= category_list.title_ch %>
        </div>
        <div class="col-md-2 col-xs-2">
            <%= category_list.category %>
        </div>
        <div class="col-md-2 col-xs-2">
            <%= category_list.parent %>
        </div>
        <div class="col-md-4 col-xs-4">
            <%= link_to "Delete", category_remove_path(category_list.id), remote: true%>
        </div>
        
    
<% end %>
</div>
    <%= form_tag category_add_path, remote: true do %>
        <div class="col-md-2 col-xs-2">Title English </div>
        <div class="col-md-10 col-xs-10"><%= text_field_tag "title_en", "" %></div>
        <div class="col-md-2 col-xs-2">Title Chinese</div>
        <div class="col-md-10 col-xs-10"><%= text_field_tag "title_ch", "" %></div>
        <div class="col-md-2 col-xs-2">Category</div>
        <div class="col-md-10 col-xs-10"><%= text_field_tag "category", "" %></div>
        <div class="col-md-2 col-xs-2">Parent</div>
        <div class="col-md-10 col-xs-10"><%= text_field_tag "parent", "" %></div>
    <%= submit_tag "Add new" %>
    <% end %>
</div>

app/views/main/category_update.js.erb
$(".update_alert").html("good").fadeIn( "fast" ).delay(800).fadeOut();

app/views/main/index.html.erb
<script>
    $(document).ready(function(){
    $('.bxslider').bxSlider({
        auto: true,
        autoControls: true
    });
    });
</script>   
    
    

<div id="main">

        <%= render partial: "module/header" %>
        
        <div class="col-md-12 col-xs-12 content">
            
            <%= render partial: "module/sideMenu" %>
            
            <div class="col-md-9 col-xs-9 info">
                    <div class="info_top"> </div>
                    <div class="info_mid"> 
                    <ul class="bxslider">
                        
                        <li><img src="/assets/img/A-C1.jpg" width="710px" /></li>
                        <li><img src="/assets/img/A-C2.jpg" width="710px"/></li>
                        <li><img src="/assets/img/A-C3.jpg" width="710px"/></li>
                        <li><img src="/assets/img/A-C4.jpg" width="710px"/></li>
                        <li><img src="/assets/img/A-C5.jpg" width="710px"/></li>
                        <li><img src="/assets/img/A-C6.jpg" width="710px"/></li>
                        <li><img src="/assets/img/A-C7.jpg" width="710px"/></li>

                    </ul>
                    </div>
                    
            </div> 
            <div class="col-md-12 col-xs-12 info_bottom"></div>
        </div>

</div>
        <%= render partial: "module/footer" %>

app/views/main/index.mobile.erb




<div id="index_carousel">
    <div><img src="/assets/img/A-C1.jpg" width="100%"/></div>
    <div><img src="/assets/img/A-C2.jpg" width="100%"/></div>
    <div><img src="/assets/img/A-C3.jpg" width="100%"/></div>
    <div><img src="/assets/img/A-C4.jpg" width="100%"/></div>
    <div><img src="/assets/img/A-C5.jpg" width="100%"/></div>
    <div><img src="/assets/img/A-C6.jpg" width="100%"/></div>
    <div><img src="/assets/img/A-C7.jpg" width="100%"/></div>
</div>
<div id="index_carousel_dots"></div>

app/views/main/room1.html.erb
<div id="main">

        <%= render partial: "module/header" %>
        
        <div class="col-md-12 col-xs-12 content">
            
            <%= render partial: "module/sideMenu" %>

            <div class="col-md-9 col-xs-9 info">
                
                <div class="info_top"> </div>
                    <div class="info_mid"> 
                       
<h1 class='title'>房型介紹</h1>
    <hr>
    <br>
    <br>
    <div class='col-md-12 col-xs-12 envi_content'>
        <div class='col-md-3 col-xs-3 envi_list'>
            <ul>
                <li class="envi_list_title">VIP房</li>
                <li class="envi_list_title"><a href="room2">尊爵房</a></li>
                <li class="envi_list_title"><a href="room3">典雅房</a></li>
            </ul>
        </div>
        <div class='col-md-9 col-xs-9 envi_img'>
            <div class='rooms_b'> <img height='272' id='big' name='big' src='/assets/img/room_1.jpg' />             </div>
            <ul class='rooms'>
                <li class='rooms_s'>
                    <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
            </ul>
        </div>
    </div>
    
                        
                    </div>
               
                    
                </div>
             <div class="col-md-12 col-xs-12 info_bottom"></div>
        </div>
    </div>
	    
</div>
            
    <%= render partial: "module/footer" %>

app/views/main/room1.mobile.erb
<div class="info_top"> </div>
<div class="info_mid"> 

<h1 class='title'>房型介紹</h1>
    <hr>
    <br>
    <br>
    <div class='col-md-12 col-xs-12 envi_content'>
        <div class='col-md-3 col-xs-3 envi_list'>
            <ul>
                <li class="envi_list_title">VIP房</li>
                <li class="envi_list_title"><a href="room2.html">尊爵房</a></li>
                <li class="envi_list_title"><a href="room3.html">典雅房</a></li>
            </ul>
        </div>
        <div class='col-md-9 col-xs-9 envi_img'>
            <div class='rooms_b'> <img height='272' id='big' name='big' src='/assets/img/room_1.jpg' />             </div>
            <ul class='rooms'>
                <li class='rooms_s'>
                    <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
            </ul>
        </div>
    </div>

</div>
 
<div class="col-md-12 col-xs-12 info_bottom"></div>

app/views/main/room2.html.erb
<div id="main">

        <%= render partial: "module/header" %>
        
        <div class="col-md-12 col-xs-12 content">
            
            <%= render partial: "module/sideMenu" %>

            <div class="col-md-9 col-xs-9 info">
                
                <div class="info_top"> </div>
                    <div class="info_mid"> 
                       
<h1 class='title'>房型介紹</h1>
    <hr>
    <br>
    <br>
    <div class='col-md-12 col-xs-12 envi_content'>
        <div class='col-md-3 col-xs-3 envi_list'>
            <ul>
                <li class="envi_list_title"><a href="room1">VIP房</a></li>
                <li class="envi_list_title">尊爵房</li>
                <li class="envi_list_title"><a href="room3">典雅房</a></li>
            </ul>
        </div>
        <div class='col-md-9 col-xs-9 envi_img'>
            <div class='rooms_b'> <img height='272' id='big' name='big' src='/assets/img/room_1.jpg' />             </div>
            <ul class='rooms'>
                <li class='rooms_s'>
                    <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
            </ul>
        </div>
    </div>

                    </div>
                    
                </div>
             <div class="col-md-12 col-xs-12 info_bottom"></div>
        </div>
    </div>
	    
</div>
            
    <%= render partial: "module/footer" %>

app/views/main/room2.mobile.erb
<div class="info_top"> </div>
<div class="info_mid"> 

<h1 class='title'>房型介紹</h1>
    <hr>
    <br>
    <br>
    <div class='col-md-12 col-xs-12 envi_content'>
        <div class='col-md-3 col-xs-3 envi_list'>
            <ul>
                <li class="envi_list_title">VIP房</li>
                <li class="envi_list_title"><a href="room2.html">尊爵房</a></li>
                <li class="envi_list_title"><a href="room3.html">典雅房</a></li>
            </ul>
        </div>
        <div class='col-md-9 col-xs-9 envi_img'>
            <div class='rooms_b'> <img height='272' id='big' name='big' src='/assets/img/room_1.jpg' />             </div>
            <ul class='rooms'>
                <li class='rooms_s'>
                    <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
            </ul>
        </div>
    </div>

</div>
 
<div class="col-md-12 col-xs-12 info_bottom"></div>

app/views/main/room3.html.erb
<div id="main">

        <%= render partial: "module/header" %>
        
        <div class="col-md-12 col-xs-12 content">
            
            <%= render partial: "module/sideMenu" %>

            <div class="col-md-9 col-xs-9 info">
                
                <div class="info_top"> </div>
                    <div class="info_mid"> 
                       
<h1 class='title'>房型介紹</h1>
    <hr>
    <br>
    <br>
    <div class='col-md-12 col-xs-12 envi_content'>
        <div class='col-md-3 col-xs-3 envi_list'>
            <ul>
                <li class="envi_list_title"><a href="room1">VIP房</a></li>
                <li class="envi_list_title"><a href="room2">尊爵房</a></li>
                <li class="envi_list_title">典雅房</li>
            </ul>
        </div>
        <div class='col-md-9 col-xs-9 envi_img'>
            <div class='rooms_b'> <img height='272' id='big' name='big' src='/assets/img/room_1.jpg' />             </div>
            <ul class='rooms'>
                <li class='rooms_s'>
                    <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
            </ul>
        </div>
    </div>
    
                    </div>
               
                    
                </div>
             <div class="col-md-12 col-xs-12 info_bottom"></div>
        </div>
    </div>
	    
</div>
            
    <%= render partial: "module/footer" %>

app/views/main/room3.mobile.erb
<div class="info_top"> </div>
<div class="info_mid"> 

<h1 class='title'>房型介紹</h1>
    <hr>
    <br>
    <br>
    <div class='col-md-12 col-xs-12 envi_content'>
        <div class='col-md-3 col-xs-3 envi_list'>
            <ul>
                <li class="envi_list_title">VIP房</li>
                <li class="envi_list_title"><a href="room2.html">尊爵房</a></li>
                <li class="envi_list_title"><a href="room3.html">典雅房</a></li>
            </ul>
        </div>
        <div class='col-md-9 col-xs-9 envi_img'>
            <div class='rooms_b'> <img height='272' id='big' name='big' src='/assets/img/room_1.jpg' />             </div>
            <ul class='rooms'>
                <li class='rooms_s'>
                    <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
                <li class='rooms_s'>
                     <img class="envi_pic_s" height="63" src="/assets/img/room_1.jpg" width="100">
                </li>
            </ul>
        </div>
    </div>

</div>
 
<div class="col-md-12 col-xs-12 info_bottom"></div>

app/views/module/_footer.html.erb
<div class="col-md-12 col-xs-12 footer_top">
</div>
<div class="col-md-12 col-xs-12 footer">
    <ul>台北市大安區忠孝東路4段221號9樓 <br/>
        管理中心TEL：02-877-16-877　FAX:02-2999-7511 │電子信箱：foryu221@gmail.com│ <br/>
        Copyright © 2014 Taiwan All Rights Reserved.     
    </ul>

</div> <!-- end of footer -->

app/views/module/_header.html.erb

<div class="header">

    <div class="col-md-6 col-xs-6 site_title">
        <a href="/" target="_parent">
            <img src="/assets/img/logo_400x120.png" alt="logo" />
        </a>
    </div>
    <div class="col-md-6 col-xs-6 shopping_cart_box">
        <img src="/assets/img/logo_2.png" alt="logo2"/>
    </div>

</div> <!-- end of templatemo_header -->

<div class="menu">
        <img src="/assets/img/border.jpg" width="100%" height="130px" />

</div> <!-- end of templatemo_menu -->

app/views/module/_sideMenu.html.erb
<div class="sidebar_box">

    <ul class="col-md-3 col-xs-3 side_bar_menu">      
        
        <% @category_list.each do |category_list| %>
            <li class="sidebar_list"><%= link_to category_list.title_ch, category_path(:title_en => category_list.title_en) %></li>       
        <% end %>
    </ul>


</div>